version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-logs
    ports:
      - "8123:8123"  # HTTP port
      - "9000:9000"  # Native port
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./config/clickhouse:/etc/clickhouse-server/config.d
    environment:
      - CLICKHOUSE_DB=system_logs
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  vector:
    image: timberio/vector:latest-alpine
    container_name: vector-logs
    volumes:
      - ./config/vector_minimal.toml:/etc/vector/vector.toml:ro
      - ./lastday.log:/var/log/lastday.log:ro
      - ./logs:/var/log/app_logs:ro
      - vector_data:/var/lib/vector
    ports:
      - "8686:8686"  # Vector API
    depends_on:
      clickhouse:
        condition: service_healthy
    restart: unless-stopped
    command: ["--config", "/etc/vector/vector.toml"]

  clickhouse-client:
    image: clickhouse/clickhouse-client:latest
    container_name: clickhouse-client
    depends_on:
      - clickhouse
    volumes:
      - ./scripts:/scripts
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
    profiles:
      - tools

volumes:
  clickhouse_data:
    driver: local
  vector_data:
    driver: local

networks:
  default:
    name: logs-network
